### ISSUE TITLE
protocol https problem

### ISSUE THREAD

**Issue by Bennyelg** [dropbox/PyHive#163]
```
      1 presto.connect(
      2                 host="host", username='user', protocol='https',
----> 3                 requests_kwargs={'auth': requests.auth.HTTPBasicAuth('user', 'secret')}
      4             ).cursor()

/usr/local/lib/python2.7/site-packages/pyhive/presto.pyc in cursor(self)
     63     def cursor(self):
     64         """Return a new :py:class:`Cursor` object using the connection."""
---> 65         return Cursor(*self._args, **self._kwargs)
     66
     67     def rollback(self):

**TypeError: __init__() got an unexpected keyword argument 'requests_kwargs'**
```

**Comment by jingw** [comment]
Can you please confirm you're using the latest version? The argument is there.
https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L81

**Comment by Bennyelg** [comment]
I do use 0.5.0.

**Comment by jingw** [comment]
You might have a stale pyc file. Try deleting your environment and starting
fresh.

On Oct 1, 2017 1:18 PM, "Benny Elgazar" <notifications@github.com> wrote:

I do use 0.5.0.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/dropbox/PyHive/issues/163#issuecomment-333403696>, or mute
the thread
