### ISSUE TITLE
support for brewed hive?

### ISSUE THREAD

**Issue by podopie** [dropbox/PyHive#23]
setting up connections using a homebrew version of hive fails because TCLIService is not in the location pyhive is expected it to be in.

pyhive is expecting `/usr/lib/hive/lib/py`, brew's location is `/usr/local/Cellar/hive/version_num/libexec/lib/py`.

Or would the solution be to just symlink the py directory specifically, instead of symlinking from the version? (issue is because brew has a libexec folder which seems to be missing from pyhive's expectation)

**Comment by jingw** [comment]
pyhive doesn't actually reference `/usr/lib/hive/lib/py`. Only the instructions reference that since it's where the files live for CDH. It imports TCLIService and lets python figure out where it actually lives.

It seems like your issue is caused by brew's celler not being in your PYTHONPATH. To fix that, you have a couple options
- Symlink the brew cellar stuff into the default python path (`print sys.path`)
- Run `PYTHONPATH=/brew/stuff python ...`
