### ISSUE TITLE
Row Transfer performance

### ISSUE THREAD

**Issue by nicku33** [dropbox/PyHive#29]
Hey this is not so much an issue as a question about expectations. Against our hiveserver I'm able to transfer appx 4-8k rows per second after the Hive query is complete and we are transferring results out. However if I write to an HDFS directory and do an hadoop fs -cat through SSH I can get 500-700k rows per second over the same network connection. This seems like a tremendous overhead. Is it due to thrift ?

**Comment by jingw** [comment]
I haven't made any effort around profiling and optimization, so the lousy performance you're observing isn't surprising. (In all my use cases, Hive/Presto/Hadoop do all the heavy lifting, and I'm just using Python for some light weight post-processing.)

Some factors:
- `hadoop fs -cat` is compiled Java code instead of Python. I wouldn't be surprised if the python Hive client was CPU bound.
- `hadoop fs -cat` just dumps the raw byte stream instead of doing things like serialization, decompression, etc.

All that said, large transfers might be better satisfied with Hive queries / MR jobs / distcp.

**Comment by nicku33** [comment]
OK, thanks for the response and the work on this library. If I find anything I'll let you know.
