### ISSUE TITLE
Hive UDF in Python  is forced to use Python2

### ISSUE THREAD

**Issue by keeyonghan** [dropbox/PyHive#31]
My team is developing Hive based workflow using Python UDF and is running it through PyHive. The UDF is written in Python3 but it didn't work (which worked fine from Hive shell). After a while (long hours of debugging), we finally figured that it is forced to use Python2 somehow (shebang line in Python script was ignored). Any idea why this is the case?

BTW thanks for the great work here!

Thanks!
Keeyong

**Comment by jingw** [comment]
I'm not sure what you mean. PyHive is just a client to Hive and it doesn't have any special code for UDFs versus built in functions. Hive is what a actually runs the UDFs. I believe you should get the same result regardless of whether you run the UDF through PyHive or the standard Hive CLI.

I guess there's something in your Hive Python UDF support that runs scripts using "python2 script.py" instead of "./script.py"?
