### ISSUE TITLE
ImportError: No module named builtins

### ISSUE THREAD

**Issue by austintrombley** [dropbox/PyHive#71]
the package won't import even though i pip upgraded and made sure i'm using pyhive-0.2.1.  I sudo pip installed future - and I am still getting this error? 

>>> from pyhive import hive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pyhive/hive.py", line 13, in <module>
    from pyhive import common
  File "/Library/Python/2.7/site-packages/pyhive/common.py", line 8, in <module>
    from builtins import bytes
ImportError: No module named builtins

**Comment by jingw** [comment]
Hi Austin,

This probably has something to do with your python environment rather than this package. Some things you can try are looking at `PYTHONPATH` in your environment, `sys.path` in a python REPL, and the results of an import in a python REPL. You might get a more useful answer from a python/pip/mac mailing list, or perhaps someone intimately familiar with your python environment.

**Comment by darkgod6** [comment]
The module "builtins" has another name in python 2.7 "__builtins__". This is the reason, why pyhive can not be imported into a python 2.7 environment.
The requirements are stated wrong, since version 0.1.8 it is no longer compatible to python 2.7.
Can you fix this?
