### ISSUE TITLE
issue a about close connection

### ISSUE THREAD

**Issue by yangzuo0621** [dropbox/PyHive#92]
Should I close the cursor instance when I fetch the data from hive? If I do not close the cursor explicitly, could it be cause memory leak.

If so, what will happen if I invoke the close function one more time ?

**Comment by jingw** [comment]
Yes, anything with a `close` should be closed. Otherwise the Hive server won't know that the client doesn't need the connection any more.

I don't think we specify the behavior of double closing, but I think I'd consider it a bug to do so. You can use `contextlib.closing` to ensure that close is called exactly once at the end.
